name: Webhook on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send a request to Discord webhook
        run: |
          curl -H "Content-Type: application/json" -X POST -d "$(cat <<EOF
          {
            "username": "GitHub",
            "content": "@everyone",
            "embeds": [
              {
                "title": "ðŸ“£ New Pull Request",
                "description": "New changes on The Local Frontend by ${{
                  github.actor }}",
                "color": 2123412,
                "author": {
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{ github.actor }}",
                  "icon_url": "https://github.com/${{ github.actor }}.png"
                },
                "url": "${{ github.event.pull_request.html_url }}"
              }
            ]
          }
          EOF
          )" ${{ secrets.DISCORD_WEBHOOK_URL }}
